In [11]:
import json
from pathlib import Path

import numpy as np
import pandas as pd
import geopandas as gpd
import networkx as nx
import xarray as xr 
import matplotlib.pyplot as plt
from shapely.geometry import Point, Polygon
from shapely.ops import unary_union
from tqdm import tqdm

target_crs = "EPSG:4326"

datasets = Path("/nas/cee-water/cjgleason/data")
proj_root = Path("/nas/cee-water/cjgleason/ted/swot-ml")

data_dir = proj_root / 'data' / 'reservoirs' 
metadata_dir = data_dir / 'metadata'
metadata_dir.mkdir(parents=True, exist_ok=True)

attributes_dir = data_dir / 'attributes'
attributes_dir.mkdir(parents=True, exist_ok=True)

fig_dir = data_dir / '_figures'
fig_dir.mkdir(parents=True, exist_ok=True)

In [ ]:
basin = 'All_MERIT'

basins = gpd.read_file(metadata_dir / f'{basin}_basins.gpkg').set_index('comid')
basins['outlet'] = [Point(xy) for xy in zip(basins['lng'], basins['lat'])]

footprint_geom = unary_union(basins.geometry.envelope)

outlets = basins.copy()
outlets = outlets.set_geometry('outlet').set_crs('EPSG:4326')

In [2]:
print("reading SWORD")
sword_dir =  datasets / 'SWORD' / 'SWORDv17' / 'shp'
sword_files = list(sword_dir.glob('*/*reaches*.shp'))
sword = pd.concat([gpd.read_file(f) for f in tqdm(sword_files)])

sword = sword.to_crs(target_crs).clip(footprint_geom)
sword['type'] = sword['reach_id']%10
sword = sword.rename(columns={'facc':'sword_area'})

# Get subset of rivers and lakes on rivers
basin_sword = sword[sword['type'].isin([1,3])]

reading SWORD

100%|██████████| 60/60 [01:21<00:00,  1.35s/it]

In [3]:
matchups = basins.reset_index()[['comid','reservoir','custom','outlet_id','total_area','unitarea','dist_downstream','outlet','geometry']]

matchups = gpd.sjoin_nearest(
    matchups.to_crs("EPSG:6933"),
    basin_sword[['reach_id', 'type', 'sword_area', 'geometry']].to_crs("EPSG:6933"),
    how='left',
    max_distance=1000,
    distance_col='sword_distance')
matchups.drop(columns='index_right', inplace=True)

matchups = matchups.to_crs('epsg:4326').reset_index(drop=True)

In [11]:
sword_pfaf2_ids = (matchups['reach_id'] // 1E9).dropna().astype(int).unique()

ms_path = datasets/"MERIT-SWORD"/"ms_translate"/"sword_to_mb"
cont_code_map = {
    1: 'AF',
    2: 'EU',
    3: 'SI',
    4: 'AS',
    5: 'AU',
    6: 'SA',
    7: 'NA',
    8: 'AR',
    9: 'GR'
}

pld_dfs = []
s2m_dfs = []
for pfaf2 in tqdm(sword_pfaf2_ids):
    cont = cont_code_map[pfaf2//10]

    s2m_ds = xr.open_dataset(ms_path / f"sword_to_mb_pfaf_{pfaf2}_translate.nc")
    s2m_dfs.append(s2m_ds.to_pandas())
    
    # Load in PLD data
    stem = f"SWOT_L2_HR_LakeAvg_024_{cont}_{pfaf2}_20241112T025038_20241202T233543_PIC2_01.shp"
    filepath = datasets / 'PLD' / 'SWOT_L2_HR_LAKEAVG' / stem
    if filepath.is_file():
        pld_dfs.append(gpd.read_file(filepath).replace({'no_data': None}).dropna(subset='reach_id'))
    else:
        print(f"{cont}_{pfaf2} is missing from PLD files")

pld = pd.concat(pld_dfs)
pld['reach_id'] = pld["reach_id"].apply(
    lambda x: x.split(";") if isinstance(x, str) and x.strip() else []
)
pld = pld.explode('reach_id')

s2m = pd.concat(s2m_dfs)

 35%|███▌      | 6/17 [01:29<03:25, 18.69s/it]

NA_72 is missing from PLD files

 88%|████████▊ | 15/17 [02:20<00:10,  5.40s/it]

AR_82 is missing from PLD files
AR_83 is missing from PLD files

100%|██████████| 17/17 [03:15<00:00, 11.48s/it]

In [16]:
s2m

,mb_1,mb_2,mb_3,mb_4,mb_5,mb_6,mb_7,mb_8,mb_9,mb_10,...,part_len_31,part_len_32,part_len_33,part_len_34,part_len_35,part_len_36,part_len_37,part_len_38,part_len_39,part_len_40
sword,,,,,,,,,,,,,,,,,,,,,
21101200013,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21101200033,21026088,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21101200041,21026067,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21101200053,21026088,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21101200063,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85209000643,85003550,85003551,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85209000655,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85209000666,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85209000676,85003198,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85209000686,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
grp_cols = ['geometry','outlet','outlet_id','total_area','unitarea','reservoir','custom']
sword_r_cols = ['reach_id','sword_area','sword_distance']
sword_l_cols = ['lake_reach_ids', 'lake_pld_ids']
all_columns = grp_cols + sword_r_cols + sword_l_cols

s2m_cols = [col for col in s2m.columns if col.startswith("mb_")]

def get_best_pair(grp):
    data_dict = {k: np.nan for k in all_columns}
    data_dict.update(grp.iloc[0][grp_cols].to_dict())

    # SWORD river reach matching.
    # Pick best match by area with a limit of 30% difference.
    rivers = grp[grp['type']==1]
    if len(rivers)>0:
        sword_area_diff = (grp['sword_area'] - grp['total_area']) / (grp[['sword_area','total_area']].mean(axis=1))
        if any(sword_area_diff.abs() < 0.3):
            idx_min = sword_area_diff.abs().idxmin()
            data_dict.update(grp.loc[idx_min][sword_r_cols].to_dict())

    # Get all SWORD lake reaches in the subbasin
    sword_lakes = grp[grp['type']==3]
    sword_lake_ids =  sword_lakes['reach_id'].astype(int).to_list()
    data_dict['lake_reach_ids'] = sword_lake_ids

    pld_ix = pld[pld['reach_id'].astype(int).isin(sword_lake_ids)]
    pld_ids = pld_ix['lake_id'].astype(int).to_list()
    data_dict['lake_pld_ids'] = list(set(pld_ids))

    # Get all MERIT basin ids corresponding to SWORD reaches
    sword_ids = grp['reach_id'].dropna().astype(int).unique()
    s2m_vals = []
    for sid in sword_ids:
        if sid in s2m.index:
            s2m_list = [s2m.at[sid, col] for col in s2m_cols]
            s2m_list = [str(x) for x in s2m_list if x != 0] # trim 0s 
            s2m_vals.extend(s2m_list)
    data_dict['s2m_values'] = s2m_vals 

    return pd.Series(data_dict)
        
matchups_clean = matchups.groupby('comid').apply(get_best_pair, include_groups=False)
matchups_clean.set_crs('epsg:4326', inplace=True)

,geometry,outlet,outlet_id,total_area,unitarea,reservoir,custom,reach_id,sword_area,sword_distance,lake_reach_ids,lake_pld_ids,s2m_values
comid,,,,,,,,,,,,,
21000001,"MULTIPOLYGON (((5.93875 47.99125, 5.93708 47.9...",POINT (5.889166666666659 47.94916666666667),EAUF-V7200010,398.5,152.9,False,False,NaN,NaN,NaN,[],[],[]
21000012,"MULTIPOLYGON (((5.79042 48.01125, 5.79042 48.0...",POINT (5.889166666666659 47.94916666666667),EAUF-V7200010,324.8,194.6,False,False,NaN,NaN,NaN,[],[],[]
21000019,"MULTIPOLYGON (((5.76042 47.56125, 5.76042 47.5...",POINT (5.684999999999993 47.53416666666667),EAUF-V7200010,5173.0,242.5,False,False,2.160280e+10,4530.071328,0.0,[],[],[]
21000021,"MULTIPOLYGON (((5.80625 47.60125, 5.80708 47.6...",POINT (5.76916666666666 47.58083333333334),EAUF-V7200010,4758.7,8.4,False,False,2.160280e+10,4278.612301,0.0,[],[],[]
21000022,"MULTIPOLYGON (((5.85875 47.57458, 5.85875 47.5...",POINT (5.80416666666666 47.57),EAUF-V7200010,4506.6,68.9,False,False,2.160280e+10,4278.612301,0.0,[],[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...
USGS-410401112134801,"MULTIPOLYGON (((-112.21458 40.96042, -112.2154...",POINT (-112.1875 41.0625),USGS-410401112134801,9900.3,296.5,False,True,NaN,NaN,NaN,[],[],[]
USGS-50035000,"MULTIPOLYGON (((-66.49208 18.29625, -66.49208 ...",POINT (-66.4592 18.3217),USGS-50037000,345.7,345.7,False,True,NaN,NaN,NaN,[],[],[]
USGS-50037000,"MULTIPOLYGON (((-66.50125 18.33125, -66.50125 ...",POINT (-66.5 18.3983),USGS-50037000,429.1,83.4,False,True,NaN,NaN,NaN,[],[],[]
USGS-50055000,"MULTIPOLYGON (((-66.01792 18.23125, -66.01792 ...",POINT (-66.0083 18.2392),USGS-50059050,232.4,232.3,False,True,NaN,NaN,NaN,[],[],[76004138]
USGS-50059050,"MULTIPOLYGON (((-66.00958 18.29708, -66.00792 ...",POINT (-66.0158 18.3292),USGS-50059050,541.3,308.9,False,True,7.650000e+10,521.845023,0.0,"[76500000093, 76500000083]",[],[]

In [21]:
import global_gauges as gg
facade = gg.GaugeDataFacade()
sites = facade.get_stations_n_days(90)

/nas/cee-water/cjgleason/ted/swot-ml/.venv/lib/python3.11/site-packages/global_gauges/facade.py:192: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat(provider_info)

In [32]:
matchups_clean['s2m_values'].apply(len).gt(0).sum()

np.int64(10610)

In [33]:
site_cols = [
    'name','area','latitude','longitude',
    'min_date','max_date',
    'min_discharge','max_discharge','mean_discharge',
    'count_discharge','provider'
]

matchups_sites = matchups_clean.merge(
    sites[site_cols], 
    left_index=True, 
    right_index=True, 
    how='left'
)
matchups_sites

,geometry,outlet,outlet_id,total_area,unitarea,reservoir,custom,reach_id,sword_area,sword_distance,...,area,latitude,longitude,min_date,max_date,min_discharge,max_discharge,mean_discharge,count_discharge,provider
comid,,,,,,,,,,,,,,,,,,,,,
21000001,"MULTIPOLYGON (((5.93875 47.99125, 5.93708 47.9...",POINT (5.889166666666659 47.94916666666667),EAUF-V7200010,398.5,152.9,False,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN
21000012,"MULTIPOLYGON (((5.79042 48.01125, 5.79042 48.0...",POINT (5.889166666666659 47.94916666666667),EAUF-V7200010,324.8,194.6,False,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN
21000019,"MULTIPOLYGON (((5.76042 47.56125, 5.76042 47.5...",POINT (5.684999999999993 47.53416666666667),EAUF-V7200010,5173.0,242.5,False,False,2.160280e+10,4530.071328,0.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN
21000021,"MULTIPOLYGON (((5.80625 47.60125, 5.80708 47.6...",POINT (5.76916666666666 47.58083333333334),EAUF-V7200010,4758.7,8.4,False,False,2.160280e+10,4278.612301,0.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN
21000022,"MULTIPOLYGON (((5.85875 47.57458, 5.85875 47.5...",POINT (5.80416666666666 47.57),EAUF-V7200010,4506.6,68.9,False,False,2.160280e+10,4278.612301,0.0,...,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USGS-410401112134801,"MULTIPOLYGON (((-112.21458 40.96042, -112.2154...",POINT (-112.1875 41.0625),USGS-410401112134801,9900.3,296.5,False,True,NaN,NaN,NaN,...,NaN,41.066564,-112.230256,2003-10-01,2025-09-08,0.006230,45.873291,11.263905,7165.0,usgs
USGS-50035000,"MULTIPOLYGON (((-66.49208 18.29625, -66.49208 ...",POINT (-66.4592 18.3217),USGS-50037000,345.7,345.7,False,True,NaN,NaN,NaN,...,347.056682,18.322438,-66.459568,1950-01-01,2025-09-08,0.240693,1857.585136,7.406389,25691.0,usgs
USGS-50037000,"MULTIPOLYGON (((-66.50125 18.33125, -66.50125 ...",POINT (-66.5 18.3983),USGS-50037000,429.1,83.4,False,True,NaN,NaN,NaN,...,409.216087,18.397448,-66.496560,2019-06-13,2025-09-08,1.265763,911.802460,11.017469,2247.0,usgs
USGS-50055000,"MULTIPOLYGON (((-66.01792 18.23125, -66.01792 ...",POINT (-66.0083 18.2392),USGS-50059050,232.4,232.3,False,True,NaN,NaN,NaN,...,232.579776,18.240705,-66.009198,1959-11-17,2025-09-08,0.294495,716.416219,6.403740,24037.0,usgs
USGS-50059050,"MULTIPOLYGON (((-66.00958 18.29708, -66.00792 ...",POINT (-66.0158 18.3292),USGS-50059050,541.3,308.9,False,True,7.650000e+10,521.845023,0.0,...,541.304824,18.340275,-66.005585,1986-12-25,2025-09-08,0.000283,3114.853125,9.193340,14128.0,usgs

In [27]:
# Read in hydroatlas
gdb_path = datasets / "HydroSHEDS" / "HydroATLAS" / "BasinATLAS_v10.gdb"
layer_name = "BasinATLAS_v10_lev12"

hydroatlas = gpd.read_file(gdb_path, layer=layer_name, engine="pyogrio", use_arrow=True)
hydroatlas.replace({'wet_cl_smj':-9999}, 13, inplace=True)
hydroatlas = hydroatlas.set_index('HYBAS_ID')

hydroatlas_filt = hydroatlas[hydroatlas.intersects(footprint_geom)]

/nas/cee-water/cjgleason/ted/swot-ml/.venv/lib/python3.11/site-packages/pyogrio/raw.py:337: RuntimeWarning: organizePolygons() received a polygon with more than 100 parts. The processing may be really slow.  You can skip the processing by setting METHOD=SKIP, or only make it analyze counter-clock wise parts by setting METHOD=ONLY_CCW if you can assume that the outline of holes is counter-clock wise defined
  table = reader.read_all()

In [34]:
outlets_buff = outlets.to_crs("EPSG:6933")
outlets_buff.geometry = outlets_buff.buffer(50000)

hybas_pairs = gpd.sjoin(
    outlets_buff,
    hydroatlas_filt.to_crs("EPSG:6933"),
    how='left',
)

hybas_area = hybas_pairs['UP_AREA']
merit_area = hybas_pairs['total_area']
hybas_pairs['hybas_area_diff'] = (hybas_area - merit_area) / ((hybas_area + merit_area)/2)

def get_best_hybas(grp):
     # Pick best match by area.
    idx_min = grp['hybas_area_diff'].abs().idxmin()
    return grp.loc[idx_min]

all_attributes = hybas_pairs.reset_index().groupby('comid').apply(get_best_hybas, include_groups=False)

In [35]:
hybas_properties = pd.read_csv(attributes_dir / "properties.txt", header=None)[0].to_list()
matchup_props = ['unitarea','reservoir','total_area','strahler_order', 'shreve_order']
all_props = matchup_props + hybas_properties + ['hybas_area_diff']
attributes = all_attributes[all_props]

attributes.index.name = 'index'
attributes.to_csv(attributes_dir / f"{basin}_attributes.csv", index=True)

In [ ]:
attributes

In [36]:
final_matchups = matchups_sites.merge(attributes['hybas_area_diff'], left_index=True, right_index=True)
final_matchups.to_file(metadata_dir / f'{basin}_matchups.gpkg')

In [ ]:
test = gpd.read_file(metadata_dir / f"{basin}_matchups.gpkg")
test['outlet_id']

In [3]:
from data import BasinDeltaTable

root_dir = data_dir / 'deltalakes' / 'training'
store = BasinDeltaTable(root_dir)

In [16]:
attributes = pd.read_csv(attributes_dir / "All_MERIT_attributes.csv", dtype={'index':str})
attributes.rename(columns={'index':'subbasin'}, inplace=True)
attributes
# store.write_static(attributes)

,subbasin,unitarea,reservoir,total_area,strahler_order,shreve_order,dis_m3_pyr,dis_m3_pmn,dis_m3_pmx,run_mm_syr,...,urb_pc_sse,nli_ix_sav,rdd_mk_sav,hft_ix_s93,hft_ix_s09,gad_id_smj,gdp_ud_sav,gdp_ud_ssu,hdi_ix_sav,hybas_area_diff
0,21000001,152.9,False,398.5,1,2,7.058,2.513,10.896,566,...,22,3417,1221,262,251,79,29174,7.526041e+08,910,-0.034201
1,21000012,194.6,False,324.8,1,2,5.616,2.026,8.950,514,...,0,1260,435,146,107,79,28128,1.498216e+08,904,0.053341
2,21000019,242.5,False,5173.0,3,11,131.817,51.097,223.180,595,...,0,2160,1237,263,303,79,29174,3.579056e+06,910,-0.007977
3,21000021,8.4,False,4758.7,3,10,125.167,48.813,214.350,661,...,2,2025,1212,197,212,79,29174,4.439960e+08,910,0.003021
4,21000022,68.9,False,4506.6,3,9,120.838,47.327,208.769,688,...,36,3988,2864,293,291,79,29174,4.020006e+09,910,0.009101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36617,USGS-410401112134801,296.5,False,9900.3,3,12,55.529,22.336,141.120,131,...,0,767,283,23,22,240,42655,4.072836e+06,925,-0.002093
36618,USGS-50035000,345.7,False,345.7,1,1,7.043,3.237,11.850,628,...,75,6115,5913,358,359,181,34887,1.969577e+09,832,-0.091982
36619,USGS-50037000,83.4,False,429.1,1,2,7.892,3.862,14.070,579,...,17,3110,1570,254,239,181,34887,1.344143e+09,832,0.167805
36620,USGS-50055000,232.3,False,232.4,1,1,3.717,1.386,7.173,583,...,23,3494,3022,278,267,181,34887,2.642213e+09,832,0.008996
36621,USGS-50059050,308.9,False,541.3,1,2,6.815,2.791,14.144,569,...,63,6062,7828,336,340,181,34887,3.952091e+09,832,0.055675