In [1]:
import json
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely import wkt
from shapely.ops import unary_union

from pathlib import Path
from tqdm.auto import tqdm

datasets = Path("/nas/cee-water/cjgleason/data")
proj_root = Path("/nas/cee-water/cjgleason/ted/swot-ml")

save_dir = proj_root / 'data' / 'multigraph'
metadata_dir = save_dir / 'metadata'
attributes_dir = save_dir / 'attributes'

matchups = gpd.read_parquet(metadata_dir / "All_MERIT_matchups.parquet").set_index('comid')
matchups.index = matchups.index.astype(str)
footprint_geom = unary_union(matchups.geometry.envelope)

# Read in hydroatlas
gdb_path = datasets / "HydroSHEDS" / "HydroATLAS" / "BasinATLAS_v10.gdb"
layer_name = "BasinATLAS_v10_lev09"

hydroatlas = gpd.read_file(gdb_path, layer=layer_name, engine="pyogrio", use_arrow=True)
hydroatlas.replace({'wet_cl_smj':-9999}, 13, inplace=True)
hydroatlas = hydroatlas.set_index('HYBAS_ID')

/nas/cee-water/cjgleason/ted/swot-ml/.venv/lib/python3.11/site-packages/pyogrio/raw.py:337: RuntimeWarning: organizePolygons() received a polygon with more than 100 parts. The processing may be really slow.  You can skip the processing by setting METHOD=SKIP, or only make it analyze counter-clock wise parts by setting METHOD=ONLY_CCW if you can assume that the outline of holes is counter-clock wise defined
  table = reader.read_all()

In [3]:
hydroatlas_filt = hydroatlas[hydroatlas.intersects(footprint_geom)]
hydroatlas_filt

,NEXT_DOWN,NEXT_SINK,MAIN_BAS,DIST_SINK,DIST_MAIN,SUB_AREA,UP_AREA,PFAF_ID,ENDO,COAST,...,hft_ix_s09,hft_ix_u09,gad_id_smj,gdp_ud_sav,gdp_ud_ssu,gdp_ud_usu,hdi_ix_sav,Shape_Length,Shape_Area,geometry
HYBAS_ID,,,,,,,,,,,,,,,,,,,,,
2.090471e+09,2.090471e+09,2.090008e+09,2.090008e+09,2742.9,2742.9,587.8,5356.2,227999910,0,0,...,187,177,86,47765,5.371887e+09,3.498405e+10,941,1.658522,0.071262,"MULTIPOLYGON (((9.98333 47.89583, 9.97696 47.8..."
2.090505e+09,2.090502e+09,2.090008e+09,2.090008e+09,2756.3,2756.3,729.6,729.6,227980960,0,0,...,150,150,15,45967,7.845448e+08,7.845449e+08,896,1.517652,0.086590,"MULTIPOLYGON (((10.24583 47.15417, 10.24673 47..."
2.090474e+09,2.090471e+09,2.090008e+09,2.090008e+09,2762.3,2762.3,509.7,509.8,227999920,0,0,...,190,190,86,47765,3.727289e+09,3.727288e+09,941,1.376472,0.061704,"MULTIPOLYGON (((9.7875 47.8875, 9.7875 47.9, 9..."
2.090483e+09,2.090480e+09,2.090008e+09,2.090008e+09,2798.9,2798.9,787.5,1358.3,227999805,0,0,...,181,173,86,50091,7.867913e+09,1.026224e+10,930,2.216932,0.094637,"MULTIPOLYGON (((10.2125 47.72917, 10.21165 47...."
2.090483e+09,2.090480e+09,2.090008e+09,2.090008e+09,2798.9,2798.9,364.9,365.0,227999804,0,0,...,163,163,86,47996,1.999762e+09,1.999761e+09,940,1.530200,0.043970,"MULTIPOLYGON (((9.82917 47.84167, 9.82286 47.8..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8.090193e+09,8.090194e+09,8.090042e+09,8.090042e+09,370.6,370.6,137.6,137.6,852049802,0,0,...,0,0,41,64789,0.000000e+00,0.000000e+00,832,0.977953,0.025887,"MULTIPOLYGON (((-69.725 64.47917, -69.725 64.4..."
8.090194e+09,8.090195e+09,8.090042e+09,8.090042e+09,385.1,385.1,136.9,137.0,852049904,0,0,...,0,0,41,64789,0.000000e+00,0.000000e+00,832,1.135298,0.025677,"MULTIPOLYGON (((-69.42917 64.42917, -69.46076 ..."
8.090194e+09,8.090195e+09,8.090042e+09,8.090042e+09,385.2,385.2,281.2,1533.0,852049905,0,0,...,0,0,41,64789,0.000000e+00,0.000000e+00,832,1.368882,0.052953,"MULTIPOLYGON (((-69.26667 64.65, -69.26575 64...."
8.090203e+09,8.090200e+09,8.090042e+09,8.090042e+09,387.3,387.3,434.9,434.9,852049609,0,0,...,0,0,41,64789,0.000000e+00,0.000000e+00,832,1.652801,0.080128,"MULTIPOLYGON (((-69.94167 63.85833, -69.94409 ..."
8.090192e+09,8.090189e+09,8.090042e+09,8.090042e+09,439.5,439.5,415.3,415.4,852049909,0,0,...,0,0,41,64789,0.000000e+00,0.000000e+00,832,1.652835,0.077777,"MULTIPOLYGON (((-68.95833 64.4, -68.96564 64.4..."

In [4]:
outlets = matchups.copy()
outlets.geometry = gpd.GeoSeries.from_wkt(outlets['outlet']).set_crs('EPSG:4326')
outlets_buff = outlets.to_crs("EPSG:6933")
outlets_buff.geometry = outlets_buff.buffer(2500)
outlets_buff

hybas_pairs = gpd.sjoin(
    outlets_buff,
    hydroatlas_filt.to_crs("EPSG:6933"),
    how='left',
)

hybas_area = hybas_pairs['UP_AREA']
merit_area = hybas_pairs['total_area']
hybas_pairs['hybas_area_diff'] = (hybas_area - merit_area) / ((hybas_area + merit_area)/2)

def get_best_hybas(grp):
     # Pick best match by area.
    idx_min = grp['hybas_area_diff'].abs().idxmin()
    return grp.loc[idx_min]

all_attributes = hybas_pairs.reset_index().groupby('comid').apply(get_best_hybas, include_groups=False)

In [5]:
all_attributes

,outlet,outlet_id,total_area,unitarea,reservoir,custom,reach_id,sword_area,sword_distance,lake_reach_ids,...,hft_ix_u93,hft_ix_s09,hft_ix_u09,gad_id_smj,gdp_ud_sav,gdp_ud_ssu,gdp_ud_usu,hdi_ix_sav,Shape_Length,Shape_Area
comid,,,,,,,,,,,,,,,,,,,,,
21000001,POINT (5.889166666666659 47.94916666666667),EAUF-V7200010,398.5,152.9,False,False,NaN,NaN,NaN,[],...,142,92,92,79,30484,2.234216e+08,2.234215e+08,899,1.265614,0.054663
21000012,POINT (5.889166666666659 47.94916666666667),EAUF-V7200010,324.8,194.6,False,False,NaN,NaN,NaN,[],...,142,92,92,79,30484,2.234216e+08,2.234215e+08,899,1.265614,0.054663
21000019,POINT (5.684999999999993 47.53416666666667),EAUF-V7200010,5173.0,242.5,False,False,2.160280e+10,4530.071328,0.0,[],...,146,169,112,79,29174,5.338522e+07,4.766761e+09,910,0.341375,0.006112
21000021,POINT (5.76916666666666 47.58083333333334),EAUF-V7200010,4758.7,8.4,False,False,2.160280e+10,4278.612301,0.0,[],...,145,143,109,79,29174,3.097191e+07,4.403724e+09,910,0.308233,0.005653
21000022,POINT (5.80416666666666 47.57),EAUF-V7200010,4506.6,68.9,False,False,2.160280e+10,4278.612301,0.0,[],...,145,143,109,79,29174,3.097191e+07,4.403724e+09,910,0.308233,0.005653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USGS-410401112134801,POINT (-112.1875 41.0625),USGS-410401112134801,9900.3,296.5,False,True,NaN,NaN,NaN,[],...,124,124,141,240,42655,2.913075e+09,8.595890e+10,925,1.084193,0.036562
USGS-50035000,POINT (-66.4592 18.3217),USGS-50037000,345.7,345.7,False,True,NaN,NaN,NaN,[],...,223,317,168,181,34887,6.136761e+09,3.651930e+05,832,1.194202,0.032871
USGS-50037000,POINT (-66.5 18.3983),USGS-50037000,429.1,83.4,False,True,NaN,NaN,NaN,[],...,238,226,226,181,34887,4.710949e+09,4.710948e+09,832,1.361730,0.052243
USGS-50055000,POINT (-66.0083 18.2392),USGS-50059050,232.4,232.3,False,True,NaN,NaN,NaN,[],...,339,336,336,181,34887,1.834885e+10,1.834885e+10,832,1.295452,0.066069
USGS-50059050,POINT (-66.0158 18.3292),USGS-50059050,541.3,308.9,False,True,7.650000e+10,521.845023,0.0,"[76500000093, 76500000083]",...,372,352,372,181,34887,3.032841e+10,8.336649e+08,832,1.651065,0.043946

In [10]:
hybas_properties = pd.read_csv(attributes_dir / "properties.txt", header=None)[0].to_list()
matchup_props = ['outlet_id', 'unitarea','reservoir','total_area']
all_props = matchup_props + hybas_properties + ['hybas_area_diff']

In [25]:
attributes = (
    all_attributes[all_props]
    .reset_index()
    .rename(columns={'comid':'subbasin', 'outlet_id': 'basin'})
    .astype({'subbasin':str, 'basin': str})
    .set_index(['basin', 'subbasin'])
)
attributes

                                           unitarea  reservoir  total_area  \
basin                subbasin
EAUF-V7200010        21000001                 152.9      False       398.5
                     21000012                 194.6      False       324.8
                     21000019                 242.5      False      5173.0
                     21000021                   8.4      False      4758.7
                     21000022                  68.9      False      4506.6
...                                             ...        ...         ...
USGS-410401112134801 USGS-410401112134801     296.5      False      9900.3
USGS-50037000        USGS-50035000            345.7      False       345.7
                     USGS-50037000             83.4      False       429.1
USGS-50059050        USGS-50055000            232.3      False       232.4
                     USGS-50059050            308.9      False       541.3

                                           dis_m3_pyr  dis_m3_pmn  dis_m3_pmx  \
basin                subbasin
EAUF-V7200010        21000001                6.031000    2.077000    9.826000
                     21000012                6.031000    2.077000    9.826000
                     21000019               76.288002   25.957001  125.834999
                     21000021               69.873001   23.823000  115.067001
                     21000022               69.873001   23.823000  115.067001
...                                               ...         ...         ...
USGS-410401112134801 USGS-410401112134801   55.528999   22.336000  141.119995
USGS-50037000        USGS-50035000           0.020000    0.009000    0.036000
                     USGS-50037000          10.798000    4.773000   20.870001
USGS-50059050        USGS-50055000          26.511999   13.490000   38.925999
                     USGS-50059050           0.782000    0.323000    1.420000

                                           run_mm_syr  inu_pc_smn  inu_pc_smx  \
basin                subbasin
EAUF-V7200010        21000001                     422           0           0
                     21000012                     422           0           0
                     21000019                     491           7           7
                     21000021                     500           0           0
                     21000022                     500           0           0
...                                               ...         ...         ...
USGS-410401112134801 USGS-410401112134801         148          70          83
USGS-50037000        USGS-50035000                564          36          40
                     USGS-50037000                561          21          39
USGS-50059050        USGS-50055000                699          25          59
                     USGS-50059050                628          55          62

                                           inu_pc_slt  ...  urb_pc_sse  \
basin                subbasin                          ...
EAUF-V7200010        21000001                       0  ...           0
                     21000012                       0  ...           0
                     21000019                      19  ...           0
                     21000021                      11  ...           0
                     21000022                      11  ...           0
...                                               ...  ...         ...
USGS-410401112134801 USGS-410401112134801          86  ...          16
USGS-50037000        USGS-50035000                 41  ...          46
                     USGS-50037000                 41  ...          17
USGS-50059050        USGS-50055000                 59  ...          51
                     USGS-50059050                 63  ...          76

                                           nli_ix_sav  rdd_mk_sav  hft_ix_s93  \
basin                subbasin
EAUF-V7200010        21000001                     728         759         142
                     21000012                     728         759         142
                     21000019                     820         759         175
                     21000021                     679         709         179
                     21000022                     679         709         179
...                                               ...         ...         ...
USGS-410401112134801 USGS-410401112134801        2257        1721         116
USGS-50037000        USGS-50035000               4931        3512         318
                     USGS-50037000               2808        1391         238
USGS-50059050        USGS-50055000               5156        4864         339
                     USGS-50059050               5910       12009         353

                                           hft_ix_s09  gad_id_smj  gdp_ud_sav  \
basin                subbasin
EAUF-V7200010        21000001                      92          79       30484
                     21000012                      92          79       30484
                     21000019                     169          79       29174
                     21000021                     143          79       29174
                     21000022                     143          79       29174
...                                               ...         ...         ...
USGS-410401112134801 USGS-410401112134801         124         240       42655
USGS-50037000        USGS-50035000                317         181       34887
                     USGS-50037000                226         181       34887
USGS-50059050        USGS-50055000                336         181       34887
                     USGS-50059050                352         181       34887

                                             gdp_ud_ssu  hdi_ix_sav  \
basin                subbasin
EAUF-V7200010        21000001              2.234216e+08         899
                     21000012              2.234216e+08         899
                     21000019              5.338522e+07         910
                     21000021              3.097191e+07         910
                     21000022              3.097191e+07         910
...                                                 ...         ...
USGS-410401112134801 USGS-410401112134801  2.913075e+09         925
USGS-50037000        USGS-50035000         6.136761e+09         832
                     USGS-50037000         4.710949e+09         832
USGS-50059050        USGS-50055000         1.834885e+10         832
                     USGS-50059050         3.032841e+10         832

                                           hybas_area_diff
basin                subbasin
EAUF-V7200010        21000001                     0.128888
                     21000012                     0.330506
                     21000019                    -0.068228
                     21000021                    -0.087447
                     21000022                    -0.033068
...                                                    ...
USGS-410401112134801 USGS-410401112134801        -0.002093
USGS-50037000        USGS-50035000                0.109379
                     USGS-50037000                0.353415
USGS-50059050        USGS-50055000                1.078052
                     USGS-50059050               -0.048439

[36622 rows x 198 columns]

In [33]:
attributes.to_parquet(attributes_dir / f"static.parquet")

In [34]:
test = pd.read_parquet(attributes_dir / "static.parquet")

In [35]:
test

                                           unitarea  reservoir  total_area  \
basin                subbasin
EAUF-V7200010        21000001                 152.9      False       398.5
                     21000012                 194.6      False       324.8
                     21000019                 242.5      False      5173.0
                     21000021                   8.4      False      4758.7
                     21000022                  68.9      False      4506.6
...                                             ...        ...         ...
USGS-410401112134801 USGS-410401112134801     296.5      False      9900.3
USGS-50037000        USGS-50035000            345.7      False       345.7
                     USGS-50037000             83.4      False       429.1
USGS-50059050        USGS-50055000            232.3      False       232.4
                     USGS-50059050            308.9      False       541.3

                                           dis_m3_pyr  dis_m3_pmn  dis_m3_pmx  \
basin                subbasin
EAUF-V7200010        21000001                6.031000    2.077000    9.826000
                     21000012                6.031000    2.077000    9.826000
                     21000019               76.288002   25.957001  125.834999
                     21000021               69.873001   23.823000  115.067001
                     21000022               69.873001   23.823000  115.067001
...                                               ...         ...         ...
USGS-410401112134801 USGS-410401112134801   55.528999   22.336000  141.119995
USGS-50037000        USGS-50035000           0.020000    0.009000    0.036000
                     USGS-50037000          10.798000    4.773000   20.870001
USGS-50059050        USGS-50055000          26.511999   13.490000   38.925999
                     USGS-50059050           0.782000    0.323000    1.420000

                                           run_mm_syr  inu_pc_smn  inu_pc_smx  \
basin                subbasin
EAUF-V7200010        21000001                     422           0           0
                     21000012                     422           0           0
                     21000019                     491           7           7
                     21000021                     500           0           0
                     21000022                     500           0           0
...                                               ...         ...         ...
USGS-410401112134801 USGS-410401112134801         148          70          83
USGS-50037000        USGS-50035000                564          36          40
                     USGS-50037000                561          21          39
USGS-50059050        USGS-50055000                699          25          59
                     USGS-50059050                628          55          62

                                           inu_pc_slt  ...  urb_pc_sse  \
basin                subbasin                          ...
EAUF-V7200010        21000001                       0  ...           0
                     21000012                       0  ...           0
                     21000019                      19  ...           0
                     21000021                      11  ...           0
                     21000022                      11  ...           0
...                                               ...  ...         ...
USGS-410401112134801 USGS-410401112134801          86  ...          16
USGS-50037000        USGS-50035000                 41  ...          46
                     USGS-50037000                 41  ...          17
USGS-50059050        USGS-50055000                 59  ...          51
                     USGS-50059050                 63  ...          76

                                           nli_ix_sav  rdd_mk_sav  hft_ix_s93  \
basin                subbasin
EAUF-V7200010        21000001                     728         759         142
                     21000012                     728         759         142
                     21000019                     820         759         175
                     21000021                     679         709         179
                     21000022                     679         709         179
...                                               ...         ...         ...
USGS-410401112134801 USGS-410401112134801        2257        1721         116
USGS-50037000        USGS-50035000               4931        3512         318
                     USGS-50037000               2808        1391         238
USGS-50059050        USGS-50055000               5156        4864         339
                     USGS-50059050               5910       12009         353

                                           hft_ix_s09  gad_id_smj  gdp_ud_sav  \
basin                subbasin
EAUF-V7200010        21000001                      92          79       30484
                     21000012                      92          79       30484
                     21000019                     169          79       29174
                     21000021                     143          79       29174
                     21000022                     143          79       29174
...                                               ...         ...         ...
USGS-410401112134801 USGS-410401112134801         124         240       42655
USGS-50037000        USGS-50035000                317         181       34887
                     USGS-50037000                226         181       34887
USGS-50059050        USGS-50055000                336         181       34887
                     USGS-50059050                352         181       34887

                                             gdp_ud_ssu  hdi_ix_sav  \
basin                subbasin
EAUF-V7200010        21000001              2.234216e+08         899
                     21000012              2.234216e+08         899
                     21000019              5.338522e+07         910
                     21000021              3.097191e+07         910
                     21000022              3.097191e+07         910
...                                                 ...         ...
USGS-410401112134801 USGS-410401112134801  2.913075e+09         925
USGS-50037000        USGS-50035000         6.136761e+09         832
                     USGS-50037000         4.710949e+09         832
USGS-50059050        USGS-50055000         1.834885e+10         832
                     USGS-50059050         3.032841e+10         832

                                           hybas_area_diff
basin                subbasin
EAUF-V7200010        21000001                     0.128888
                     21000012                     0.330506
                     21000019                    -0.068228
                     21000021                    -0.087447
                     21000022                    -0.033068
...                                                    ...
USGS-410401112134801 USGS-410401112134801        -0.002093
USGS-50037000        USGS-50035000                0.109379
                     USGS-50037000                0.353415
USGS-50059050        USGS-50055000                1.078052
                     USGS-50059050               -0.048439

[36622 rows x 198 columns]